server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;

    location = /MadsjeezSellerBrowserSetup.exe {
        add_header Access-Control-Allow-Origin *;
        add_header Content-Disposition 'attachment; filename="MadsjeezSellerBrowserSetup.exe"';
        default_type application/octet-stream;
    }

    location = / {
        return 302 /MadsjeezSellerBrowserSetup.exe;
    }

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
