server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    autoindex on;

    location / {
        add_header Access-Control-Allow-Origin *;
        add_header Content-Disposition 'attachment; filename="MadsjeezSellerBrowser-v0.1.0-win-x64.zip"';
    }

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
